/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jenkins.plugins.mttr;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import com.google.common.io.Files;
import hudson.model.AbstractProject;
import java.io.File;
import java.io.IOException;
import jenkins.plugins.util.StoreUtil;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.mockito.Mockito;

/** @author nick */
public class BuildMetricAllTimeResultColumnTest {

  @Rule public TemporaryFolder temporaryFolder = new TemporaryFolder();

  private static final String EXPECTED_MTTR_7_MILLIS = "5200";

  private static final String EXPECTED_MTTR_30_MILLIS = "5300";

  private static final String EXPECTED_MTTR_ALL_MILLIS = "5400";
  private static final String EXPECTED_MTTR_ALL_AS_STRING = "5.4 sec";

  /**
   * Test of getResult method, of class BuildMetricAllTimeResultColumn.
   *
   * @throws IOException maybe raised by CreateMockProject
   */
  @Test
  public final void testGetResult() throws IOException {
    AbstractProject project = createMockProject();
    createAMockMTTRPropertiesFileIn(project.getRootDir());

    ResultColumn resultColumn = new BuildMetricAllTimeResultColumn();
    assertEquals(
        "MTTR_All_DAYS is incorrect",
        EXPECTED_MTTR_ALL_AS_STRING,
        resultColumn.getResult(project));
  }

  /**
   * Test of getGraph method, of class BuildMetricAllTimeResultColumn.
   *
   * @throws IOException may be raised by createMockProject
   */
  @Test
  public final void testGetGraph() throws IOException {
    AbstractProject project = createMockProject();
    BuildMetricAllTimeResultColumn instance =
        new BuildMetricAllTimeResultColumn();

    assertNull(instance.getGraph(project));
  }

  /**
   * Creates a Mock Project for use in the test.
   *
   * @return The mock Project
   * @throws IOException maybe generated by newFolder
   */
  private AbstractProject createMockProject() throws IOException {
    AbstractProject job = Mockito.mock(AbstractProject.class);
    File rootFolder = temporaryFolder.newFolder();
    Mockito.when(job.getRootDir()).thenReturn(rootFolder);
    return job;
  }

  /**
   * * Create a Mock Properties file for use in tests when we want the file in a
   * particular state.
   *
   * @param rootFolder the root folder for the test, where the file will be
   *     generated
   * @throws IOException could be generated by Files.write
   */
  private void createAMockMTTRPropertiesFileIn(final File rootFolder)
      throws IOException {
    String s =
        MetricsAction.MTTR_LAST_7_DAYS + "\t" + EXPECTED_MTTR_7_MILLIS + "\n";
    s +=
        MetricsAction.MTTR_LAST_30_DAYS + "\t" + EXPECTED_MTTR_30_MILLIS + "\n";
    s += MetricsAction.MTTR_ALL_BUILDS + "\t" + EXPECTED_MTTR_ALL_MILLIS + "\n";

    Files.write(
        s.getBytes(),
        new File(
            rootFolder.getAbsolutePath()
                + File.separator
                + StoreUtil.MTTR_PROPERTY_FILE));
  }
}
